### ISSUE TITLE
Getting Subject 'no-more' response

### ISSUE THREAD

**Issue by srallen** [zooniverse/Chimp-Zoo#101]
Occasionally calling `Subject.next()` is getting a no more subjects response. This is incorrect since several new subject groups have been processed and are uploaded. The no more subjects response only started happening when the new subject groups were uploaded and activated. It is related to the duplicate subject and duplicate classification issue in #98. Maybe possibly related to the bad subject id issue in #96? Any ideas @astopy or @parrish why this is happening? Also we are being asked in #98 if the new subject groups can be paused until this is resolved.

**Comment by parrish** [comment]
This should be fixed now.  A group had completed, but hadn't properly changed state.
