### ISSUE TITLE
Future site videos up

### ISSUE THREAD

**Issue by jwidness** [zooniverse/Chimp-Zoo#105]
Cold Fire and Restless Star videos are showing up in classification -- I sort of assume this isn't on purpose since Dawn Bird doesn't seem close to done yet.  Any way we can get these taken out of the active pool?

For reference, http://talk.chimpandsee.org/#/subjects/ACP000b84i is a cold fire video that came up, and http://talk.chimpandsee.org/#/subjects/ACP000bvqj is a restless star video that came up.

**Comment by astopy** [comment]
This is working as intended. There are currently 17,984 active subjects in Dawn Bird. To keep the minimum of 20,000 active the system has activated new groups.
