### ISSUE TITLE
Mouseover image on small grey duiker during classification is wrong

### ISSUE THREAD

**Issue by jwidness** [zooniverse/Chimp-Zoo#108]
The image is actually of a bush duiker.

**Comment by srallen** [comment]
@jwidness Could you let me know what image should be used for the small grey duiker? It's the same image in the field guide too: 
![screen shot 2016-03-07 at 2 33 36 pm](https://cloud.githubusercontent.com/assets/5016731/13582401/bca373da-e471-11e5-9630-d38e0a7c077d.png)

**Comment by jwidness** [comment]
The first image in the field guide looks the most like what we get on camera (for obvious reasons).  I could find another image for the mouseover if you'd prefer something else, though.  I didn't notice the full image of the bush duiker there in the field guide -- could you take that out while you're at it?  Thanks so much!

**Comment by srallen** [comment]
@jwbmartin Could you update the sprite image we use for the field guide?:
https://github.com/zooniverse/Chimp-Zoo/blob/master/public/assets/chimps-tooltips-sprite.jpg

The small gray duiker (as seen above in the tool tip) needs to use a crop from the first image from the guide:
https://github.com/zooniverse/Chimp-Zoo/blob/master/public/assets/guide/sm-gray-duiker-1.jpg

I found the original psd on creative cloud: https://assets.adobe.com/files?location=https%3A%2F%2Fcc-us1-prod.adobesc.com%2Fapi%2Fv1%2Fcollections%2F6972c9b2-b07c-4318-941e-f9b4aa128fd4

Thanks!

**Comment by jwidness** [comment]
Thanks!
