### ISSUE TITLE
Incorrect range shown on map image

### ISSUE THREAD

**Issue by ksigler** [zooniverse/Chimp-Zoo#109]
The summary screen map for our current site is incorrect.  It doesn't show the full range of the species of chimps we're currently working with.  Can this be corrected, please?

The map is for region D, as seen here https://github.com/zooniverse/Chimp-Zoo/blob/master/public/assets/summary/site-d.jpg

The correct range for P.t.schweinfurthii is the gray area (with & without red stripes) seen here: http://panafrican.eva.mpg.de/english/where_we_work.php  Notice that it should include the areas further east in Uganda, Rwanda, and Tanzania.

We could provide a corrected map if it would help the turnaround time.  Thanks.

**Comment by srallen** [comment]
@jwbmartin do you have time this week to correct the image for the site location? I see the original illustrator file in [creative cloud](https://assets.adobe.com/files?location=https%3A%2F%2Fcc-us1-prod.adobesc.com%2Fapi%2Fv1%2Fcollections%2F907d990a-3948-4ce0-9be1-bd25f925fc62) at that URL.

**Comment by jwbmartin** [comment]
@srallen @ksigler Yeah I can totally do that (also yay I get to work on maps!)

**Comment by jwidness** [comment]
Looks great, thanks!
