### ISSUE TITLE
Comments stuck

### ISSUE THREAD

**Issue by AnLand** [zooniverse/Chimp-Zoo#112]
Comments stuck both in recents (video comments) and at the discussions board (since an hour probably). Talk should be operational and classification works too. Not sure about error message.

Button grays out and nothing happens.

**Comment by yshish** [comment]
browser consoles shows many errors of this type: *Failed to load resource: the server responded with a status of 404 (Not Found)*

**Comment by AnLand** [comment]
Error message:

	
403 Forbidden
		20ms
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"
>
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request.
 The distribution supports only cachable requests.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: m_LTqzz1GmqKynd_IofCVrQSqHts64_uVXSrXnLdgtfm3XeSl7ra1w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by yshish** [comment]
The same problem is on the Science Gossip Talk..

**Comment by yshish** [comment]
After trying to post a comment on Chimp, the console shows:
*Failed to load resource: the server responded with a status of 403 (Forbidden)* 

and when I try to post a comment or to collect an image (it doesn't work either) on SG, it shows:

*POST http://www.sciencegossip.org/_ouroboros_api/projects/illustratedlife/talk/collections/CSCS00008q/add_subject 403 (Forbidden)u.ajaxTransport.c.send @ api-cb2090271be4f48643a394566a5e4d4b.js:16u.extend.ajax @ api-cb2090271be4f48643a394566a5e4d4b.js:16(anonymous function) @ api-cb2090271be4f48643a394566a5e4d4b.js:17u.event.dispatch @ api-cb2090271be4f48643a394566a5e4d4b.js:15u.event.add.s.handle @ api-cb2090271be4f48643a394566a5e4d4b.js:15*

Can't tell what it means. Hope it is helpful.

**Comment by eatyourgreens** [comment]
Pinging @astopy and @camallen since CloudFront is rejecting the request when you post a new comment.

**Comment by jwidness** [comment]
This looks like it might be a bigger problem -- I checked the status page and no classifications have been recorded for the last 2 hours.  I then went to classify a video (happened to be a red duiker), and it has no red duiker counters on it after my classification.  ACP000cc3d

**Comment by yshish** [comment]
It affect more old project Talks like Penguins and SG but not Kelp nor Plankton.

**Comment by camallen** [comment]
This is a problem affecting our old API infrastructure, we're working on it.

**Comment by camallen** [comment]
see https://status.zooniverse.org/ for more information.

**Comment by camallen** [comment]
this was resolved, see the status site for more details.
