### ISSUE TITLE
Mixed content (http/https) causing some screen elements to not load

### ISSUE THREAD

**Issue by ksigler** [zooniverse/Chimp-Zoo#117]
I mentioned this before in  #116 but that specific issue was resolved.  Unfortunately, the mix of secure and insecure content is now affecting different areas of the site.  Specifically, the paging control on collections on the Talk pages, as well as the video skin.  There is a discussion about it among users [here](https://talk.chimpandsee.org/#/boards/BCP0000009/discussions/DCP0000wuv).  Just bringing it up again, since I'm not sure what is still being worked on regarding the secure and insecure content.

If it helps, I'm attaching the console log for https://talk.chimpandsee.org/#/subjects/ACP000ceyw
 as seen when I don't instruct Chrome to allow the unsafe content:
[talk.chimpandsee.org-1458698057408.txt](https://github.com/zooniverse/Chimp-Zoo/files/185291/talk.chimpandsee.org-1458698057408.txt)

Thanks.

**Comment by astopy** [comment]
Ideally we should fix all of those, but it'll just be the first two blocked requests that are causing the problems:

```
Mixed Content: The page at 'https://talk.chimpandsee.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://vjs.zencdn.net/4.1/video-js.css'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://talk.chimpandsee.org/' was loaded over HTTPS, but requested an insecure script 'http://vjs.zencdn.net/4.1/video.js'. This request has been blocked; the content must be served over HTTPS.
```

I'll have a fix for that shortly.
