### ISSUE TITLE
FAQ button disappears under animated chimp

### ISSUE THREAD

**Issue by AnLand** [zooniverse/Chimp-Zoo#120]
I am not sure whether it is only me, but it is impossible to click the new FAQ button in the nav bar as it disappears under the animated chimp when moving over that space. Why we don't replace the "FAQs" button (and link) within the upper black bar (that goes to a crowded discussion board!) with the link to the actual FAQ posting?

**Comment by srallen** [comment]
@AnLand Could you let me know what browser and device you're seeing this issue with the link on? Also, possibly upload a screenshot?

**Comment by AnLand** [comment]
MacBook Pro, 13'', Mozilla Firefox (same in Chrome, I tried)

![bildschirmfoto 2016-04-04 um 17 42 07](https://cloud.githubusercontent.com/assets/7421089/14253757/15b5b812-fa8d-11e5-8783-5e3db890ee1e.jpg)
![bildschirmfoto 2016-04-04 um 17 41 56](https://cloud.githubusercontent.com/assets/7421089/14253758/15b8c55c-fa8d-11e5-8141-0df36f68c73f.jpg)
