### ISSUE TITLE
After a chimp video, "Site Chimp ID Board" button doesn't work -- fix included

### ISSUE THREAD

**Issue by jwidness** [zooniverse/Chimp-Zoo#122]
After you classify a video as containing a chimp, the summary page has a button labeled "Site Chimp ID Board" (see image).  This button doesn't go to the ID boards for cold fire or restless star.  I'm assuming the fix is to make the field "known_chimps_link" go to the correct URL.  So we should have for restless star "new_chimps_link":"http://talk.chimpandsee.org/#/boards/BCP000000q" and for cold fire "new_chimps_link":"http://talk.chimpandsee.org/#/boards/BCP000000r".
Thanks!

<img width="702" alt="chimpsummarypage" src="https://cloud.githubusercontent.com/assets/13769652/14318556/690f9830-fbdb-11e5-87c3-450add16ae69.png">

**Comment by astopy** [comment]
These have been added now (along with the known chimps links for both groups).

**Comment by jwidness** [comment]
Thanks!

**Comment by jwidness** [comment]
Could you add https://talk.chimpandsee.org/#/boards/BCP000000s as the new_chimps_link for aged violet?  Thanks!

**Comment by astopy** [comment]
Done!
