### ISSUE TITLE
"Search" function broken on Chimpandsee Talk page

### ISSUE THREAD

**Issue by AnLand** [zooniverse/Chimp-Zoo#156]
Hi! The "Search" function on the Chimp&See Talk page is broken and does not return any results for searches anymore. It was reported by three volunteers (including myself) and I tested for Firefox and Google Chrome. As nothing happens at all if you enter a search term and press the respective "Search" button, it could be the search function or just the button. Could you please check this, the search is needed, but we posted a work-around with a google search specified for only the talk.chimpandsee.org website.

Here the Talk discussion: https://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP0002im0 that additionally reports a delay in adding to manual collections and the Recents (own classified videos) of some minutes.

Thank you!

**Comment by adammcmaster** [comment]
Thanks for the report. This is working again now.
