### ISSUE TITLE
"On the ground" button submitting extra behaviors [bad news]

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#61]
A couple of users are reporting sporadic issues with marking duikers that are "on the ground."

They say that marking a duiker (especially a red duiker, I guess?) as "on the ground" occasionally causes one of two other tags--"traveling" or "drinking/feeding" to be automatically added.

Having trouble replicating. Asking for more info. Any idea?

http://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP00000jl

**Comment by DarrenMcRoy** [comment]
More reports on this. It seems like the "on the ground" button sporadically adds a bonus behavior to the classification. It doesn't just select the button... it adds (and submits) the extra behavior to your finished classification.

This is BAD because it means that people are submitting erroneous classifications by no fault of their own, which could corrupt the science.

It's extremely difficult to hunt down because it cannot be reliably reproduced, but we know that it is always caused by selecting "on the ground" and the behavior that is added is what was marked in the previous subject.

Quia, bless her, has done a detailed breakdown here: http://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP00000jl?page=2&comment_id=553e4cdbf3464404f800000f

This strikes me as a priority thing because classifications are being corrupted. Thoughts @srallen ?

**Comment by srallen** [comment]
I've been working on this since Friday afternoon. It doesn't have anything to do with the specific animal or behavior that is chosen, but rather how react-cursor is handling a shallow merge with the currentAnswers store. I'm reworking it and may have a fix this morning.

**Comment by DarrenMcRoy** [comment]
Excellent news. Thank you for the update!!
