### ISSUE TITLE
Build the list of chimp-video IDs

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#66]
On the list of important things to do for C&S: build that list of all videos IDed as having chimps for the sites that have been completed, so that the chimp-ID can be completed for those sites.

I believe @chrissnyder was going to do that sometime early this week?

Thanks!!

**Comment by chrissnyder** [comment]
Done and online at http://www.chimpandsee.org/identified-chimps/
