### ISSUE TITLE
Same video in the system twice with different object IDs?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#68]
It looks like a few videos from Red Water 6 got processed and put into the system twice?

ACP00030jv and ACP00030w9 are the same video, and users say these are not the only ones.

Quia found that they appear to come from these files, with the same "EK000152.AVI" but one of them in an extra folder, or something.

IvoryCoast_TaiE/A4/TAI-E_CAM_21_0680324_0653118_2013_06_06/CHIMP/EK000152.AVI

IvoryCoast_TaiE/A4/TAI-E_CAM_21_0680324_0653118_2013_06_06/EK000152.AVI

What's up here?

**Comment by chrissnyder** [comment]
I didn't do any sort of checksum checks against the subject pool. If they included a video twice on the hard drive, then it was uploaded twice onto the site. Looks to be the case for the provided example.
