### ISSUE TITLE
Some users can't scroll all the way down on the field guide

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#70]
We've had reports, almost since launch, of users not being able to scroll to the bottom of the Field Guide, getting hung up/locked up somewhere around "leopard."

http://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP00002uo?page=1&comment_id=554d0298a77a1b50d200015b

It seems like it might just be a problem in certain browsers, but it's something I've been ignoring the sporadic reports of for a while, and figured I should probably put it into GitHub. Any idea, @srallen ?

**Comment by srallen** [comment]
I'm using viewport units for the height which some older browsers had bugs with particularly older iOS Safari and Android browser. Could you please have the users report specifically what OS and browser with version numbers they're using (i.e. iPad 2 with iOS Safari 7.1 or Windows 7 with IE 10, etc)?

**Comment by DarrenMcRoy** [comment]
On it...
