### ISSUE TITLE
Twitter link has an incorrect connection

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#71]
A user points out this little thing with the Tweet button:

There is a connection shown "via @chimp" that is not the correct Twitter feed. It should be "via @chimpandsee"

That is correct; @chimpandsee is the correct feed. Tweakable?

**Comment by srallen** [comment]
Where is this supposed to be? The share button for twitter just posts "Classifying on the Zooniverse!" with the talk subject link. There aren't any links going to a chimpandsee twitter account anywhere on the site.

**Comment by DarrenMcRoy** [comment]
I'm not entirely sure. I thought that it might be something in the code that indicated the referral.

Let me see if I can figure out a bit more what the user is talking about...

**Comment by eatyourgreens** [comment]
Might be this line in the Talk config?
https://github.com/zooniverse/Talk/blob/master/projects/chimp/config.coffee#L6

**Comment by srallen** [comment]
Good catch @eatyourgreens. @DarrenMcRoy, will you open a ticket for this on the Talk repo? Thanks.
