### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by pmgreen** [zooniverse/Chimp-Zoo#74]
I'm currently able to log in to Zooniverse as usual but not into Chimpandsee. Have tried in different browsers, etc. The 'forgot your password?' option goes to to https://www.zooniverse.org/#/reset-password, which doesn't work when one is still logged into the main site.

**Comment by DarrenMcRoy** [comment]
I'd like to add that there have been a disturbing number of reports to this effect:  able to sign in on the main page, but not into certain projects.  Although it has been for a couple of different reasons.

 Question: are you using your username?  Not your email address?  Email address login only works on the main page.

**Comment by pmgreen** [comment]
Yes, username, almost always via a password manager (so it's not a matter of misspellings).

**Comment by chrislintott** [comment]
I get the same problem on Chrome 44.0.2403.125.
