### ISSUE TITLE
Field guide update to mention viverrids

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#79]
A few updates:

CHANGE "SMALL CAT" TO:

Several species of small felines can be found in Africa, including the caracal, the serval, the African golden cat, and the African wildcat. Any cat smaller than a leopard or a cheetah can be classified as a "small cat." Please note that viverrids, like civets and genets, are not cats, and should be marked as "other."

CHANGE "OTHER" TO:

Mark any animal that does not fall into the above categories as "other." This includes cat-like viverrids like the civet and genet.

Add these images to "other":

![5520365569736d72e6514401_2](https://cloud.githubusercontent.com/assets/8987864/9310497/a3d8f032-44d5-11e5-8d50-19421b2ab5e6.jpg)

![5520397369736d72e6db5b02_0](https://cloud.githubusercontent.com/assets/8987864/9310505/ad665fea-44d5-11e5-86f9-e794ec5983a1.jpg)

**Comment by chrissnyder** [comment]
:+1:

**Comment by srallen** [comment]
This is in production.
