### ISSUE TITLE
Lingering Shape site location map not displaying

### ISSUE THREAD

**Issue by jwidness** [zooniverse/Chimp-Zoo#80]
After classifying lingering shape videos, instead of seeing the site location map, I just get a broken image icon.

**Comment by srallen** [comment]
Fixed in 99769a3d34f37406ddcc814234556d523095fe3f

**Comment by jwidness** [comment]
Same problem again for lingering shape part 2.

**Comment by yshish** [comment]
And for current DryLake data too!

**Comment by srallen** [comment]
The second lingering shape group is fixed. Dry Lake appears to have a different issue with getting the map. Still working on it.

**Comment by jwidness** [comment]
I'm now not getting maps for either lingering shape or dawn bird -- I haven't had any dry lake videos in a while, can't comment on that.

**Comment by srallen** [comment]
@jwidness, the maps are fixed. The most recent issue with them was my mistake when working on the site this weekend, but it's fixed now.
