### ISSUE TITLE
Dry Lake is running low on subjects

### ISSUE THREAD

**Issue by jwidness** [zooniverse/Chimp-Zoo#94]
Just wanted to make sure that someone is on top of it :)

**Comment by srallen** [comment]
Yes, @astopy is working on it.

**Comment by astopy** [comment]
New data is up now.

**Comment by AnLand** [comment]
There seems to be a problem with the newly loaded videos in the "Recents". Video format is not supported.

**Comment by jwidness** [comment]
Thanks!  This should keep us busy for a very long time!
