### ISSUE TITLE
Newly loaded videos - not supported in "Recents"

### ISSUE THREAD

**Issue by AnLand** [zooniverse/Chimp-Zoo#95]
There seems to be a problem with the newly loaded videos in the "Recents". Video format is not supported.

**Comment by srallen** [comment]
Looks like the Recent subjects array is returning empty for the new subjects. Video encoding doesn't appear to have any relation.

**Comment by AnLand** [comment]
Can you do anything? Message says (in German) no supported videos are found.

**Comment by srallen** [comment]
Yeah, it's falling back to the error message for the html video tag, which I made to be about video format. But, the call for Recents isn't returning SubjectsForRecent, so the video sources aren't being set. I'm taking a look at it now to make sure it isn't something in the front end code.

**Comment by astopy** [comment]
I think I know what's causing this. I should have it fixed today.

**Comment by astopy** [comment]
Recents should be working again now.
